### ISSUE TITLE
Collections are not children of a catalog

### ISSUE THREAD

**Issue by matthewhanson** [fredliporace/cbers-2-stac#19]
I'm not sure if this is this technically follows the spec (I think it does), but collections are only linked to from the Items, they don't appear in the catalog tree directly (they have no parent or root, and do not appear as child links from the root or any sub-catalog).

I think that the collections should appear (or at least should be part of Best Practices) within the catalog structure so you can get a a list of collections from traversing the catalogs and not having to go all the way to the Item level to get the collection.  This means you have to follow every Item to get a list of all the Collections in a catalog.

Having the collections between the root catalog and items also makes ingesting the catalog easier.  sat-api assumes this structure as it then ingests a Collection before any Items that are part of that Collection.

**Comment by fredliporace** [comment]
I chose that way to make the use of collections easier when migrating from 0.5 to 0.6. It followed the spec as defined at the moment.

I checked and placing root/collections at the root directory is defined as best practice in dev.

Structure will be reorganized for the 0.7 implementation

**Comment by fredliporace** [comment]
Closed in dev, new 0.7 structure (beta not complete archive) may be browsed from https://cbers-stac-0-7.s3.amazonaws.com/CBERS4/catalog.json
