### ISSUE TITLE
Invalid Collection Names with dynamic API

### ISSUE THREAD

**Issue by matthewhanson** [fredliporace/cbers-2-stac#20]
The collection names in the CBERS catalog are problematic due to the "/", e.g., "CBERS4/AWFI"

In a STAC API we reference collections as:

/collections/<cid>

and further parameters are recognized as parameters rather than as part of the collection ID, e.g.,

/collections/<cid>/items/

**Comment by fredliporace** [comment]
Yes, I agree. I'll change the collection IDs for 0.7

It would be nice to have this noted in the collection spec, currently it simply defines as 'string' but the ```/``` character (and possibly others) should definitely be forbidden.

**Comment by fredliporace** [comment]
Names changed in 0.7 STAC service.
/collections endpoint available [here](https://stac.amskepler.com/v07/collections)
