### ISSUE TITLE
Collection ID not included in Items

### ISSUE THREAD

**Issue by matthewhanson** [fredliporace/cbers-2-stac#21]
For STAC 0.6.x, Collection ID should be provided as the 'collection' property under Items. Collection is currently only provided as a link.

For STAC 0.7 I believe the Collection ID will move to the top level of the STAC Item.

**Comment by fredliporace** [comment]
I checked 0.6.0 and it seems that the collection ID in Items was added in one of the minor versions updates. 0.6.0 requires only the URL to the collection.

My plan is to generate a 0.7.0 catalog version as soon as the spec is released, so it does not make sense to update from 0.6.0 at this point and generate the whole catalog.

 Will keep this issue open to check the Collection ID in the new implementation.

**Comment by fredliporace** [comment]
Closed in dev
