### ISSUE TITLE
Cannot subscribe to new Item SNS

### ISSUE THREAD

**Issue by matthewhanson** [fredliporace/cbers-2-stac#22]
When trying to add
```
arn:aws:sns:us-east-1:769537946825:cbers-2-stac-0-6-CBERSSTACItemTopic-X1VTPGK5HBZ5
```

as a trigger to a Lambda for ingestion, I get a 'not authorized to perform'. 

By default SNS topics can't be subscribed to by people outside the account, you need to go into the permissions and allow subscription by everyone.  Not sure if this is the problem or not.

**Comment by fredliporace** [comment]
@matthewhanson thanks for noticing, the stack is updated and it should work now for lambda and sqs protocols.

**Comment by fredliporace** [comment]
@matthewhanson the 0.6 CBERS STAC service will be shutdown on Sep 13th. It will be replaced by the already operational 0.7 CBERS STAC service. The ARN for the 0.7 SNS topic is:

```
arn:aws:sns:us-east-1:769537946825:cbers-2-stac-0-7-CBERSSTACItemTopic-1I8YI0IIYL0R5
```

Note that collections names were changed to avoid some characters, for a list of the new collection IDs check [here](https://stac.amskepler.com/v07/collections).

I recommend subscribing to the [CBERS on AWS mailing list](https://lists.osgeo.org/mailman/listinfo/cbers-pds) for future updates.
