### ISSUE TITLE
CBERS 04A on AWS

### ISSUE THREAD

**Issue by jsscgrnt** [fredliporace/cbers-2-stac#41]
Dear Frederico,

I would like to ask you if is there any plans to CBERS 04A image be available at CBERS on AWS repository (https://registry.opendata.aws/cbers/). 

I think this channel is not the most appropriete one to ask such question and I appologize about it.

Any information about CBERS 04A on AWS will be very useful for me.

Thank you very much.

**Comment by fredliporace** [comment]
Hi @jsscgrnt , yes, there are plans to do that!

I invite you to subscribe and check the archive of the CBERS-PDS list at https://lists.osgeo.org/mailman/listinfo/cbers-pds , I'll post the updates there.
