### ISSUE TITLE
search_phase_execution_exception

### ISSUE THREAD

**Issue by fredliporace** [fredliporace/cbers-2-stac#77]
Search endpoint is currently raising the following exception:
```
Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.'
```

**Comment by fredliporace** [comment]
First occurrence at `2021-10-15T08:36:21.380-03:00`. No stack update event in the past months.

**Comment by felippehsk** [comment]
First of all, thank you so much for putting this STAC and keeping it running, @fredliporace. 

Do we have any updates in this issue? The error still keeps showing...

**Comment by fredliporace** [comment]
Service is back online

**Comment by felippehsk** [comment]
@fredliporace , thank you so much for working on this and putting the service back on! Cheers!

**Comment by fredliporace** [comment]
Noticed now that the same error is happening again at the [live version](https://stac.amskepler.com/v100/search). The stac index mappings seems to be one automatically created, although the [auto creation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation) should be disabled exactly for these kind of problems to be reported by DLQs messages as the index is corrupted.

The mapping for `geometry` for example should be `geo_shape` but is currently the default `text`.

Although the software may be improved to detect this situation sooner and allow a proper index recovery from the backup, the reason this situation pops up now and then in the live service is its es cluster configuration - I'm using a single node `t2.small.search`, which is clearly inadequate for a production service.

Unfortunately the Opensearch service is the main drive of cost in operating the live version and I don't have plans now to upgrade to a suitable configuration for production service. I'll then keep the live version limited to support testing, with only a subset of the AWS archive, which may be reset from time to time if such index corruption happens again. Organizations or individuals interested in running a full production service should be able to do so using new deployments.

Note that this only affects the STAC API search, the static STAC index in the live version reflects the complete AWS archive.

**Comment by fredliporace** [comment]
Service now covers all archive, thanks to AWS support.
