### ISSUE TITLE
No New CBERS4-MUX data since 2022-05-13

### ISSUE THREAD

**Issue by keithpeck** [fredliporace/cbers-2-stac#85]
We are subscribed to the CBERS4-MUX SNS topic and have noticed that no new data has been acquired since 2022-05-13. This is reflected in the STAC API [https://stac.amskepler.com/v100/search?datetime=2022-05-14T00:00:00Z/2023-01-01T23:59:59Z&collections=CBERS4-MUX](https://stac.amskepler.com/v100/search?datetime=2022-05-14T00:00:00Z/2023-01-01T23:59:59Z&collections=CBERS4-MUX)
 
Do you know why this is the case? Scheduled downtime for the satellite or an issue?

Thanks,
Keith

**Comment by fredliporace** [comment]
Hi @keithpeck,

Just checked INPE`s CBERS4 [catalog](http://www.dgi.inpe.br/catalogo/) and the last MUX scenes are from 2022-05-31, so this is not an INPE->AWS ingestion issue.

I'm not aware of any satellite downtime or issue, will contact INPE through their support service at atus@inpe.br and post updates here.

**Comment by keithpeck** [comment]
Thanks for investigating @fredliporace. Much appreciated.
